-- MySQL Script generated by MySQL Workbench
-- Tue May 30 13:50:17 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `freez_recipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `freez_recipes` (
  `id_recipes` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `instructions` TEXT NULL,
  PRIMARY KEY (`id_recipes`),
  UNIQUE INDEX `id_recipes_UNIQUE` (`id_recipes` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `freez_ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `freez_ingredients` (
  `id_ingredients` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_ingredients`),
  UNIQUE INDEX `id_ingredients_UNIQUE` (`id_ingredients` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `freez_recipes_ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `freez_recipes_ingredients` (
  `id_recipes` INT UNSIGNED NOT NULL,
  `id_ingredients` INT UNSIGNED NOT NULL,
  `amount` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_recipes`, `id_ingredients`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
